apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: landingpage
  name: landingpage
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: landingpage
  type: NodePort
